<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Hostedpci
 * @package     Hostedpci_Hpci
 * @author      Adam Chetverkin (adam.chetverkin@snowcommerce.com)
 * @copyright   Copyright (c) 2016 Snow Commerce (http://snowcommerce.com)
 * @license     @ Snow Commerce
 */

$_configVars = Mage::helper('hpci')->getConfigVars();

$months = Mage::getSingleton('payment/config')->getMonths();

$years = Mage::getSingleton('payment/config')->getYears();
$years = array(0 => $this->__('Year')) + $years;

$cards = Mage::getModel('hpci/card')->getCustomerCards(Mage::getSingleton('customer/session')->getCustomerId());
$types = Mage::getModel('hpci/card')->getCcTypes();

$addressId = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form action="" method="post" id="address-validate" <?php echo ($addressId)? 'class="hidden"' : '' ?> autocomplete="off">
    <div  class="auction-card-form">
        <?php echo $this->getBlockHtml('address_form') ?>
    </div>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('billing_note')->toHtml(); ?>
</form>

<form action="" method="post" id="card-validate" <?php echo $addressId?'':'class="hidden" ' ?>autocomplete="off">
    <?php echo $this->getBlockHtml('formkey') ?>
    <div class="auction-card-form">

        <div id="cartslist" class="fieldset panel cartslist  <?php echo $addressId?'':'hidden' ?>">
        <h2 class="fieldset-title"> <?php echo $this->__('Credit Cards Information') ?></h2>
        <?php foreach ($cards as $card): ?>
            <div class="panel fieldset ">
                <h2 class="legend">
                    <?php echo $this->__(($card->getIsDefault() ? 'Default' : 'Additional') . ' Credit Card') ?>
                    <?php if (Mage::getStoreConfig('hpci/settings/delete_default_card') or !$card->getIsDefault()): ?>
                        <a href="<?php echo $this->getUrl('hpci/cards/delete', array('id' => $card->getId())) ?>" onclick="return confirm('<?php echo $this->__('Delete Card') ?>?')"><?php echo $this->__('Delete Card') ?></a>
                    <?php endif; ?>
                    <?php if (!$card->getIsDefault()): ?>
                        <a href="<?php echo $this->getUrl('hpci/cards/default', array('id' => $card->getId())) ?>" onclick="return confirm('<?php echo $this->__('Make it Default?') ?>?')"><?php echo $this->__('Make it Default') ?></a>
                    <?php endif; ?>
                </h2>
                <b><?php echo $this->__('Nickname') ?>:</b> <?php echo $card->getNickname() ? $card->getNickname() : 'empty' ?>
                <br>
                <b><?php echo $this->__('Type') ?>:</b> <?php echo $card->getCcTypeName() ?><br>
                <b><?php echo $this->__('Number') ?>:</b> <?php echo $card->getCcNumberLast4() ?><br>
                <b><?php echo $this->__('Exp Date') ?>:</b> <?php echo $card->getCcExpMonth() ?>/<?php echo $card->getCcExpYear() ?>
                <br>
            </div>
        <?php endforeach; ?>
        </div>

        <div class="panel fieldset addcart ">
            <h2 class="legend">
                <?php echo $this->__('Add Credit Card') ?>
            </h2>
            <div data-parent="#form-validate" class="collapse panel-content <?php if (Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>in <?php endif; ?> ">
                <ul class="form-list">
                    <li>
                        <ul class="form-list" id="payment_form_hpci">
                            <li>
                                <label for="hpci_cc_type" class="required"><?php echo $this->__('Credit Card Type') ?></label>
                                <div class="input-box">
                                    <select id="hpci_cc_type" name="payment[cc_type]" title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry">
                                        <option value=""><?php echo $this->__('--Please Select--') ?></option>
                                        <?php $_ccType = $this->getInfoData('cc_type') ?>
                                        <?php foreach ($types as $_typeCode => $_typeName): ?>
                                            <option value="<?php echo $_typeCode ?>"><?php echo $_typeName ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </li>
                            <li style="font-size: 1px;line-height: 1;padding: 0;margin: 0;">
                                <?php if (!isset($_configVars['hpci_url']) || $_configVars['hpci_url'] == '' || !isset($_configVars['hpci_location']) || $_configVars['hpci_location'] == '' || !isset($_configVars['hpci_sid']) || $_configVars['hpci_sid'] == '') : ?>
                                    <?php echo Mage::helper('hpci')->__('This mode is not configured properly. Please inform to our web master.') ?>
                                <?php else: ?>
                                    <iframe width="100%" height="132" frameborder="0" scrolling="NO" src="<?php echo $_configVars['hpci_url'] ?>?locationName=<?php echo $_configVars['hpci_location'] ?>&amp;sid=<?php echo $_configVars['hpci_sid'] ?>&amp;fullParentHost=<?php echo urlencode(Mage::helper('core/url')->getCurrentUrl()); ?>&amp;pgmode1=prod&amp;fullParentQStr=" name="hpciframe" id="hpciframe">If you can see this, your browser doesn't understand IFRAME.</iframe>
                                    <div width="200px" style="float:left;display:none" id="validation_advice" class="validation-advice">
                                        <?php
                                        if (isset($_configVars['error_msg']) && ($_configVars['error_msg'] <> ""))
                                        {
                                            echo $_configVars['error_msg'];
                                        }
                                        else
                                        {
                                            echo $this->__("Please Enter a Valid Credit Card Info");
                                        }
                                        ?>
                                    </div>
                                    <input type="hidden" id="hpci_acc_cc_number" name="payment[cc_number]" class=""/>
                                    <input type="hidden" id="hpci_acc_cc_id" name="payment[cc_cid]" class=""/>
                                <?php endif; ?>

                                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                                <div class="tool-tip" id="payment-tool-tip" style="display:none;">
                                    <div class="btn-close">
                                        <a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a>
                                    </div>
                                    <div class="tool-tip-content">
                                        <img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>"/>
                                    </div>
                                </div>
                                <br/>
                            </li>
                            <li>
                                <br/>
                                <label for="hpci_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> </label>
                                <div class="input-box">
                                    <select id="hpci_expiration" style="width:120px;" name="payment[cc_exp_month]" class="validate-cc-exp required-entry">
                                        <option value=""><?php echo $this->__('Month') ?></option>
                                        <?php foreach ($months as $k => $v): ?>
                                            <option value="<?php echo $k ?>"><?php echo $v ?></option>
                                        <?php endforeach ?>
                                    </select>
                                    <select id="hpci_expiration_yr" style="width:80px;" name="payment[cc_exp_year]" class="required-entry">
                                        <?php foreach ($years as $k => $v): ?>
                                            <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </li>
                                <input type="hidden" id="hpci_cc_save" <?php echo count($cards)?'disabled':'' ?> name="payment[save_cc]" value="1">
                                <?php if(Mage::getStoreConfig('hpci/settings/manage_cards')): ?>
                                    <li>
                                        <label for="hpci_nickname" class="required"><?php echo $this->__('Credit Card Nickname') ?></label>
                                        <div class="input-box">
                                            <input type="text" id="hpci_nickname" name="payment[nickname]" title="<?php echo $this->__('Credit Card Nickname') ?>" class="required-entry">
                                        </div>
                                    </li>
                                    <?php if(count($cards) > 0): ?>
                                        <li>
                                            <label for="hpci_cc_default"><?php echo Mage::helper('payment')->__('Make Default Card') ?></label>
                                            <input type="checkbox" id="hpci_cc_default" <?php echo count($cards)?'disabled':'' ?> name="payment[default_cc]" value="1">
                                        </li>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <input type="hidden" id="hpci_cc_nickname" name="payment[nickname]" value="My Card">
                                    <input type="hidden" id="hpci_cc_default" <?php echo count($cards)?'disabled':'' ?> name="payment[default_cc]" value="1">
                                <?php endif; ?>
                        </ul>
                    </li>
                </ul>

                <div class="buttons-set">
                    <button type="button" title="<?php echo $this->__('Add Card') ?>" class="button" onclick="sendHPCIMsg(); return false;">
                        <span><span><?php echo $this->__('Add Card') ?></span></span>
                    </button>
                    <a href="javascript:;" id="editBilling">Edit Address</a>
                </div>
            </div>
        </div>

    </div>

    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('card_note')->toHtml(); ?>

</form>



<script type="text/javascript">
    //<![CDATA[
    function toggleToolTip(event) {
        if ($('payment-tool-tip')) {
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)) + 10 + 'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if ($('payment-tool-tip-close')) {
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    $$('.cvv-what-is-this').each(function (element) {
        Event.observe(element, 'click', toggleToolTip);
    });
    //]]>
</script>
<script>
    (function () {
        var addrForm = $('address-validate'),
                addrValid = new Validation(addrForm),
                cardForm = $('card-validate');

        function createField(n, v) {
            var field = document.createElement('input');
            field.name = n;
            field.type = 'hidden';
            field.value = v;
            cardForm.appendChild(field);
        }

        $('address-validate').observe('submit', function (e) {
            e.stop();
            if (addrValid.validate()) {
                $('address-validate').addClassName('hidden');
                $('card-validate').removeClassName('hidden');
                <?php if (count($cards)): ?>
                    $('cartslist').removeClassName('hidden');
                <?php endif ?>
                var addressData = $(addrForm).serialize(true);
                $H(addressData).each(function (th) {
                    if (typeof th.value == 'string') {
                        createField(th.key, th.value);
                    } else {
                        th.value.each(function (arr) {
                            createField(th.key, arr);
                        });
                    }
                });
            }
        });
        $('editBilling').observe('click', function() {
            $('address-validate').removeClassName('hidden');
            $('card-validate').addClassName('hidden');
        });
    })();

    hpciCCFrameHost = "https://cc.hostedpci.com";


    desktop_location = "<?php echo $_configVars['hpci_location'] ?>";
    mobile_location = "managecardsmobile";

    hpciCCFrameFullDesktopUrl = "<?php echo $_configVars['hpci_url'] ?>?locationName=<?php echo $_configVars['hpci_location'] ?>&sid=<?php echo $_configVars['hpci_sid'] ?>&fullParentHost=<?php echo urlencode(Mage::helper('core/url')->getCurrentUrl());?>&<?php if($oscCheck){?>pgmode1=prod&<?php }?>fullParentQStr=";
    hpciCCFrameFullMobileUrl = "<?php echo $_configVars['hpci_url'] ?>?locationName=" + mobile_location + "&sid=<?php echo $_configVars['hpci_sid'] ?>&fullParentHost=<?php echo urlencode(Mage::helper('core/url')->getCurrentUrl());?>&<?php if($oscCheck){?>pgmode1=prod&<?php }?>fullParentQStr=";

    hpciCCFrameFullUrl = hpciCCFrameFullDesktopUrl;


    hpciCCFrameName = "hpciframe";

    var hpciForm = new VarienForm('card-validate');

    function hpciSiteErrorHandler(errorCode, errorMsg) {
        if (errorMsg) {
            jQuery('#opc-review').css('opacity', "0");
            setTimeout(function () {
                if (jQuery('#hpci_acc_cc_type').val() != "") {
                    jQuery('#validation_advice').css("display", '');
                }
                jQuery('#opc-review').css('opacity', "1");

            }, 800);
            return false;
        }
        return true;
    }

    function hpciSiteSuccessHandler(mappedCCValue, mappedCVVValue) {
        var ccNumInput = document.getElementById("hpci_acc_cc_number");
        ccNumInput.value = mappedCCValue;

        var ccCVVInput = document.getElementById("hpci_acc_cc_id");
        ccCVVInput.value = mappedCVVValue;

        hpciForm.submit();
    }
    function saveHPCIAddress(){
        $('address-validate').submit()
    }
</script>
