<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Hostedpci
 * @package     Hostedpci_Hpci
 * @author      Adam Chetverkin (adam.chetverkin@snowcommerce.com)
 * @copyright   Copyright (c) 2016 Snow Commerce (http://snowcommerce.com)
 * @license     @ Snow Commerce
 */
?>
<?php
$_code = $this->getMethodCode();
$_configVars = Mage::helper('hpci')->getConfigVars();

$cards = array();
$types = Mage::getModel('hpci/card')->getCcTypes();

$cid = Mage::getSingleton('customer/session')->getCustomerId();
$manageCards = Mage::getStoreConfig('hpci/settings/manage_cards');

if($cid and Mage::getStoreConfig('hpci/settings/manage_cards'))
{
    $cards = Mage::getModel('hpci/card')->getCustomerCards($cid);
}
?>
<?php /** @TODO: WE NEED TO DISPLAY FEW CARDS INSTEAD OF ONE */ ?>
<div class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
    <ul id="hpci_card_info_new" style="<?php echo count($cards) ? 'display: none' : '' ?>">
        <li>
            <label for="<?php echo $_code ?>_cc_type" class="required"><?php echo $this->__('Credit Card Type') ?></label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry" <?php echo count($cards)?'disabled':'' ?>>
                    <option value=""><?php echo $this->__('--Please Select--') ?></option>
                    <?php $_ccType = $this->getInfoData('cc_type') ?>
                    <?php foreach ($types  as $_typeCode => $_typeName): ?>
                        <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </li>
        <li style="font-size: 1px;line-height: 1;padding: 0;margin: 0;">
            <?php if(!isset($_configVars['hpci_url']) || $_configVars['hpci_url'] == '' || !isset($_configVars['hpci_location']) || $_configVars['hpci_location'] == '' || !isset($_configVars['hpci_sid']) || $_configVars['hpci_sid'] == '') : ?>
                <?php echo Mage::helper('hpci')->__('This mode is not configured properly. Please inform to our web master.')?>
            <?php else: ?>
                <iframe width="100%" height="80" frameborder="0" scrolling="NO" src="<?php echo $_configVars['hpci_url'] ?>?locationName=<?php echo $_configVars['hpci_location'] ?>&amp;sid=<?php echo $_configVars['hpci_sid'] ?>&amp;fullParentHost=<?php echo urlencode(Mage::helper('core/url')->getCurrentUrl());?>&amp;pgmode1=prod&amp;fullParentQStr=" name="hpciframe" id="hpciframe">If you can see this, your browser doesn't understand IFRAME.</iframe>
                <div width="200px" style="float:left;display:none" id="validation_advice" class="validation-advice">
                    <?php
                    if(isset($_configVars['error_msg']) && ($_configVars['error_msg']<>""))
                    {
                        echo $_configVars['error_msg'];
                    }
                    else
                    {
                        echo "Please Enter a Valid Credit Card Info";
                    }
                    ?>
                </div>
                <input type="hidden" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]"  class="" <?php echo count($cards)?'disabled':'' ?> />
                <input type="hidden" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" class="" <?php echo count($cards)?'disabled':'' ?> />
            <?php endif; ?>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
            <br/>
        </li>
        <li>
            <br/>
            <label for="<?php echo $_code ?>_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?></label>
            <div class="input-box">

                <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="validate-cc-exp required-entry" <?php echo count($cards)?'disabled':'' ?>>
                    <option value=""><?php echo $this->__('Month') ?></option>
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach (Mage::getSingleton('payment/config')->getMonths() as $k=>$v): ?>
                        <option value="<?php echo $k ?>" <?php if($k==$_ccExpMonth && !is_null($_ccExpMonth)): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry" <?php echo count($cards)?'disabled':'' ?>>
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k ? $k : '' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </li>
        <?php if($manageCards): ?>
            <li>
                <label for="<?php echo $_code ?>_save"><?php echo Mage::helper('payment')->__('Save Card') ?></label>
                <input type="checkbox" id="<?php echo $_code ?>_save" <?php echo count($cards)?'disabled':'' ?> name="payment[save_cc]" value="1">
            </li>
            <?php if(count($cards) > 0): ?>
                <li>
                    <label for="<?php echo $_code ?>_default"><?php echo Mage::helper('payment')->__('Make Default Card') ?></label>
                    <input type="checkbox" id="<?php echo $_code ?>_default" <?php echo count($cards)?'disabled':'' ?> name="payment[default_cc]" value="1">
                </li>
            <?php endif; ?>
        <?php endif; ?>
    </ul>
    <?php if(count($cards)): ?>
        <?php $card = $cards->getFirstItem(); ?>
        <div id="hpci_card_info_existing" style="/*display: none*/">
            <p>
                <strong><?php echo $this->__('Type')?>:</strong> <?php echo $card->getCcTypeName() ?><br>
                <strong><?php echo $this->__('Number')?>:</strong> <?php echo $card->getCcNumberLast4() ?><br>
                <strong><?php echo $this->__('Exp Date')?>:</strong> <?php echo $card->getCcExpMonth() ?>/<?php echo $card->getCcExpYear() ?><br>
            </p>
            <input type="hidden" name="payment[cc_type]" value="<?php echo $card->getCcType() ?>">
            <input type="hidden" name="payment[cc_id]" value="<?php echo $card->getCcCid() ?>">
            <input type="hidden" name="payment[cc_number]" value="<?php echo $card->getCcNumber() ?>">
            <input type="hidden" name="payment[cc_exp_month]" value="<?php echo $card->getCcExpMonth() ?>">
            <input type="hidden" name="payment[cc_exp_year]" value="<?php echo $card->getCcExpYear() ?>">
        </div>
        <div id="hpci_card_info_selector">
            <a href="#" style="display: none" id="hpci_card_info_existing_a" onclick="return showCcForm('hpci_card_info_existing');"><?php echo $this->__('Use Existing Card')?> <i><?php echo $card->getCcNumberLast4() ?></i></a>
            <a href="<?php echo Mage::getUrl('hpci/cards/',array('_secure'=>true)); ?>" id="hpci_card_info_new_a" onclick="return showCcForm('hpci_card_info_new');"><?php echo $this->__('Use Another Card')?></a>
        </div>
    <?php endif; ?>
</div>

