<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Hostedpci
 * @package     Hostedpci_Hpci
 * @author      Adam Chetverkin (adam.chetverkin@snowcommerce.com)
 * @copyright   Copyright (c) 2016 Snow Commerce (http://snowcommerce.com)
 * @license     @ Snow Commerce
 */

echo $this->htmlEscape($this->getMethod()->getTitle())

?>
<br />

Credit Card Type: <?php echo Mage::helper('hpci')->getCcTypeName($this->getInfo()->getCcType()) ?><br>
Credit Card Number: <?php echo sprintf('xxxx-%s', $this->getInfo()->getCcLast4() ? $this->getInfo()->getCcLast4() : substr($this->getInfo()->getCcNumber(), strlen($this->getInfo()->getCcNumber())-4)) ?><br>
