<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Hostedpci
 * @package     Hostedpci_Hpci
 * @author      Adam Chetverkin (adam.chetverkin@snowcommerce.com)
 * @copyright   Copyright (c) 2016 Snow Commerce (http://snowcommerce.com)
 * @license     @ Snow Commerce
 */
?>
<div class="page-head">
    <h3><?php echo Mage::helper('hpci')->__('Please pay your order now') ?></h3>
</div>
<table style="width:100%;">
    <tr>
        <td style="width:75%">
            <iframe style="width:100%; height:600px;" src="<?php echo Mage::getUrl('hpci/processing/placeform') ?>"></iframe>
        </td>
        <td style="text-align:center;">
            <img src="<?php echo $this->getHpciLogoSrc() ?>" title="Powered by Hpci" alt="Powered by Hpci" />
        </td>
    </tr>
</table>
