<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Hostedpci
 * @package     Hostedpci_Hpci
 * @author      Adam Chetverkin (adam.chetverkin@snowcommerce.com)
 * @copyright   Copyright (c) 2016 Snow Commerce (http://snowcommerce.com)
 * @license     @ Snow Commerce
 */
$ccTypeName = $this->getInfo()->getCcType()
    ? Mage::helper('hpci')->getCcTypeName($this->getInfo()->getCcType())
    : Mage::helper('payment')->__('N/A');
?>
<?php echo $this->getMethod()->getTitle() ?>
    {{pdf_row_separator}}
<?php if ($this->getInfo()->getLastTransId() == ''): ?>
    <?php echo Mage::helper('hpci')->__('Payment has not been processed yet.') ?>
<?php else: ?>
    <?php $paymentData = unserialize($this->getInfo()->getOrder()->getHpciPaymentData()); ?>
    <?php echo Mage::helper('hpci')->__('Credit Card Type: %s', $ccTypeName) ?>
    {{pdf_row_separator}}
    <?php echo Mage::helper('hpci')->__('Credit Card Number: %s', 'xxxx-' .$this->getInfo()->getCcLast4()) ?>
<?php endif; ?>
{{pdf_row_separator}}
